version: "3"
services:
  note-taking-app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - "8000:3000"
    environment:
      - DB_URL=mongodb://note_tacking_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  db:
    image: mongo
    container_name: note_tacking_db
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: 